### ISSUE TITLE
MSVC 14 compatibility

### ISSUE THREAD

**Issue by aelr** [matt-42/iod#10]
I tried to compile this with VS2015 Update 1 and, lo and behold, it failed to compile.  The first place it fell over is the line below, with `enable_if_t`:
https://github.com/matt-42/iod/blob/master/iod/grammar.hh#L97

``` c++
  decltype(auto) exp_transform_iterate(E& exp, F map,
                             C ctx,
                             std::enable_if_t<!callable_with<F, E&, C>::value and
                             !has_transform_iterate<E>::value>* = 0)
```

I'm just diving back into C++ after several years away, so this syntax is quite foreign.  Specifically, MSVC fails at the `and` (expecting `>`).  Is this a specific C++14 feature that VS2015 hasn't implemented?  I took a look a brief look at SFINAE and `enable_if_t` but couldn't find any relevant compatibility shortcoming in the following table:

http://en.cppreference.com/w/cpp/compiler_support

Any help to get my bearings on what is happening here would be greatly appreciated (as I'm not actually expecting MSVC support).

**Comment by duckie** [comment]
It is a bug of MSVC I already stumbled upon. There is quite a lot of them actually. This can be worked around with std::less.

**Comment by matt-42** [comment]
I just tried VS 2015 and it seems to have way to much bugs in its C++14 implementation to make iod compile on this platform. Regarding your problem specifically: replacing and by && is a workaround, but it won't make iod compile.
You should try clang on vs2015, it has less problems with c++14: https://blogs.msdn.microsoft.com/vcblog/2015/12/04/clang-with-microsoft-codegen-in-vs-2015-update-1/

**Comment by aelr** [comment]
Ah, very cool.  I'll give Clang on Windows a try.  Thanks for taking a look.
