### ISSUE TITLE
JSON encoding of integers fails for zero and negative values

### ISSUE THREAD

**Issue by Kazuo256** [matt-42/iod#14]
[This method](https://github.com/matt-42/iod/blob/master/iod/json.hh#L174) has two bugs:

1. If `t == 0`, the `while` never executes, thus the integer zero is encoded as an empty string.

2. If `t < 0`, `t % 10` will yield negative values, encoding the numbers incorrectly.

I could make a PR with a possible fix. Is that ok?

**Comment by matt-42** [comment]
Good catch ! Yes your PR is welcome. I'll review and merge it as soon as you submit it.
