### ISSUE TITLE
Cannot make iod

### ISSUE THREAD

**Issue by bblackcblackc** [matt-42/iod#24]
Centos 7, clang5

$ cmake ..
-- The C compiler identification is Clang 5.0.1
-- The CXX compiler identification is Clang 5.0.1
-- Check for working C compiler: /usr/local/bin/clang
-- Check for working C compiler: /usr/local/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/clang++
-- Check for working CXX compiler: /usr/local/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.53.0
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/data/Soft/clang/iod/ff

$ cmake --build .
Scanning dependencies of target iod_generate_symbols
[  3%] Building CXX object tools/CMakeFiles/iod_generate_symbols.dir/iod_generate_symbols.cc.o
[  6%] Linking CXX executable iod_generate_symbols
[  6%] Built target iod_generate_symbols
Scanning dependencies of target parse_command_line
[  9%] Building CXX object tests/CMakeFiles/parse_command_line.dir/parse_command_line.cc.o
In file included from /opt/data/Soft/clang/iod/tests/parse_command_line.cc:10:
In file included from /opt/data/Soft/clang/iod/tests/symbols.hh:2:
In file included from /opt/data/Soft/clang/iod/tests/../iod/symbol.hh:5:
In file included from /opt/data/Soft/clang/iod/tests/../iod/grammar.hh:6:
In file included from /opt/data/Soft/clang/iod/tests/../iod/foreach.hh:4:
In file included from /opt/data/Soft/clang/iod/tests/../iod/callable_traits.hh:3:
In file included from /opt/data/Soft/clang/iod/tests/../iod/typelist.hh:4:
/opt/data/Soft/clang/iod/tests/../iod/tuple_utils.hh:48:41: error: no template named 'enable_if_t' in namespace 'std'; did you mean 'enable_if'?
  decltype(auto) arg_get_by_type_( std::enable_if_t<!std::is_same<E,
                                   ~~~~~^~~~~~~~~~~
                                        enable_if
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/type_traits:1766:12: note: 'enable_if' declared here
    struct enable_if 
           ^
In file included from /opt/data/Soft/clang/iod/tests/parse_command_line.cc:10:
In file included from /opt/data/Soft/clang/iod/tests/symbols.hh:2:
In file included from /opt/data/Soft/clang/iod/tests/../iod/symbol.hh:5:
In file included from /opt/data/Soft/clang/iod/tests/../iod/grammar.hh:6:
In file included from /opt/data/Soft/clang/iod/tests/../iod/foreach.hh:4:
In file included from /opt/data/Soft/clang/iod/tests/../iod/callable_traits.hh:3:
In file included from /opt/data/Soft/clang/iod/tests/../iod/typelist.hh:4:
/opt/data/Soft/clang/iod/tests/../iod/tuple_utils.hh:49:41: error: no template named 'decay_t' in namespace 'std'; did you mean 'decay'?
                                   std::decay_t<T1>>::value>*,
                                   ~~~~~^~~~~~~
                                        decay


How can i fix it?

**Comment by bblackcblackc** [comment]
All ok. I think i just have an old glibc.

**Comment by Lewiscowles1986** [comment]
I'm getting this exact same error would you mind telling me which commands you ran?
