### ISSUE TITLE
FYI – alternative symbol generator/extractor CLI tool

### ISSUE THREAD

**Issue by fish2000** [matt-42/iod#8]
It’s a work in progress but I thought you might be interested:

https://github.com/fish2000/iod-symbolizer/

… I wrote it to e.g.: conditionally extract all symbols from .hpp/.hh/.cpp/.cc/.mm files in directories {aa/src, bb/src, aa/include, bb/include} – originally for one project but now I have spun it off. Written in Python, runs quick enough to use it as a CMake target 💯

Salud – thanks again for releasing your work

-Alex

**Comment by matt-42** [comment]
Hi fish2000
Nice one. Less hacky than the iod C++ symboliser. Thanks for sharing. I'll put a note in the doc about this project.

Matthieu
